
name : Check Nix Flake

on:
  pull_request:

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            extra-trusted-public-keys = gh-nix-idris2-packages.cachix.org-1:iOqSB5DrESFT+3A1iNzErgB68IDG8BrHLbLkhztOXfo=
            extra-substituters = https://gh-nix-idris2-packages.cachix.org
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update example flake file
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          cd examples/control_curses_ticker
          sed -i "s/ncurses-idris\/main/ncurses-idris\/${BRANCH_NAME}/" flake.nix
          nix flake lock
          cd -
      - name: Build flake
        run: nix build
      - name: Check flake
        run: nix flake check
